### ISSUE TITLE
Example JSON is invalid

### ISSUE THREAD

**Issue by shadowhand** [wheniwork/wheniwork-api#31]
<img width="809" alt="screenshot 2015-09-01 08 47 51" src="https://cloud.githubusercontent.com/assets/38203/9605950/45a37278-5086-11e5-880a-1acba165f760.png">

Looks like this was made invalid in [the standardize JSON commit](https://github.com/wheniwork/wheniwork-api/commit/657dd312c5c87402f0700847756cf721ed341c71#diff-3a66f2f873a9349e3e32c9b3489a2175R65).

**Comment by bvisness** [comment]
Looks like we just never deployed it. Commit #29 was actually created in part to fix that specific error.

It's now deployed and verifiable at http://dev.wheniwork.com/?php#login.

**Comment by shadowhand** [comment]
Thanks!
